# Generated by Django 4.0.3 on 2022-04-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=33)),
                ('course', models.CharField(max_length=120)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=3)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
