# Generated by Django 4.0.3 on 2022-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sell_delete_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New')], max_length=100, null=True),
        ),
    ]
