# Generated by Django 4.0.3 on 2022-04-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sell_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='condition',
            field=models.CharField(default='Brand New', max_length=100),
        ),
    ]
