# Generated by Django 4.0.3 on 2022-04-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_sell_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='condition',
            field=models.CharField(blank=True, default='Brand New', max_length=100, null=True),
        ),
    ]
