# Generated by Django 4.0.3 on 2022-04-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_brand_category_country_alter_sell_price_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
